---

- name: apache-install
  hosts: node1
  remote_user: student
  become: yes
  tasks:
    - name: install apache2
      apt:
        name=apache2
        update_cache=yes
        state=present
    - name: enable mod_rewrite
      apache2_module:
        name=rewrite
        state=present
    - name: apache2 listen on port 8082
      lineinfile:
        dest=/etc/apache2/ports.conf regexp="^Listen 80"
        line="Listen 8082"
        state=present
    - name: apache2 virtualhost on port 8082
      lineinfile:
        dest=/etc/apache2/sites-available/000-default.conf regexp="^<VirtualHost \*:80>"
        line="<VirtualHost *:8082>"
        state=present
    - name: restart apache
      service:
        name: apache2
        state: restarted
